# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

In [295]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

In [220]:
def owner(documents):
    number = str(input('Введите номер документа: '))
    owner = ''
    for line in documents:
        if line['number'] == number:
            owner = line['name']
    if owner == '':
        owner = 'Документ не найден'  
    return owner

In [221]:
owner(documents)

Введите номер документа: 11-2


'Геннадий Покемонов'

In [222]:
def location(number, directories):
    location = ''
    for key, value in directories.items():
        if number in value:
            location = key
    if location == '':
        location = 'Документ не найден в базе'
    return location

In [225]:
def full_info(documents, directories):
    for line in documents:
        print(  '№:', line['number'],\
                ', тип:', line['type'],\
                ', владелец: ',line['name'],\
                'полка хранения: ', location(line['number'], directories)
             )

In [226]:
full_info(documents, directories)

№: 2207 876234 , тип: passport , владелец:  Василий Гупкин полка хранения:  1
№: 11-2 , тип: invoice , владелец:  Геннадий Покемонов полка хранения:  1
№: 10006 , тип: insurance , владелец:  Аристарх Павлов полка хранения:  2


In [227]:
def shelf(shelf, directories):
    if shelf in directories.keys():
        print('Такая полка уже существует. Текущий перечень полок: ', list(directories.keys()))
    else:
        directories[shelf]=[]
        print('Полка добавлена. Текущий перечень полок: ', list(directories.keys()))

In [228]:
def remove(directories):
    number = input('Введите номер полки: ')
    if number not in directories:
        print('Такой полки не существует. Текущий перечень полок:', list(directories.keys()))
    elif directories[number] == []:
        del(directories[number])
        print('Полка удалена. Текущий перечень полок:', list(directories.keys()))
    elif directories[number] != []:
        print('На полке есть документы, удалите их перед удалением полки. Текущий перечень полок:', list(directories.keys()))

In [229]:
def main(documents, directories):
    while True:
        comand = input('Введите команду: ')
        if comand == 'p':
            print(owner(documents))
        elif comand == 's':
            print(location(str(input('Введите номер документа: '))), directories)
        elif comand == 'l':
            print(full_info(documents, directories))
        elif comand == 'ads':
            print(shelf(str(input('Введите номер полки: '))), directories)
        elif comand == 'ds':
            print(remove(directories))
        elif comand == 'q':
            break
        else:
            print('Такой команды нет')

In [131]:
main(documents, directories)

Введите команду: l
№: 2207 876234 , тип: passport , владелец:  Василий Гупкин полка хранения:  1
№: 11-2 , тип: invoice , владелец:  Геннадий Покемонов полка хранения:  1
№: 10006 , тип: insurance , владелец:  Аристарх Павлов полка хранения:  2
None
Введите команду: d
Такой команды нет
Введите команду: q


## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [230]:
def add_doc(documents, directories):
    doc_number = input('Введите номер документа: ')
    doc_type = input('Введите тип документа: ')
    owner = input('Введите владельца документа: ')
    shelf_num = input('Введите полку для хранения документа: ')
    if shelf_num not in directories.keys():
        print('Такой полки не существует. Добавьте полку командой ads.')
        print(full_info())
    else:
        documents.append({'type': doc_type, 'number': doc_number, 'name': owner})
        directories[shelf_num].append(doc_number)

In [261]:
def remove_doc(documents, directories):
    number = input('Введите номер документа: ')
    exist = 0
    for line in documents:
        if number in line.values():
            #line.clear()
            exist = 1
            break
        else:
            exist = 0
            #print('Документ не найден в базе.')
            #print('Текущий перечень документов:')
            #print(full_info(documents, directories))
    if exist == 0:
        print('Документ не найден в базе.')
        print('Текущий перечень документов:')
        print(full_info(documents, directories))
    else:
        documents.remove(line)
        print('Документ удален.')
        print('Текущий перечень документов:')
        print(full_info(documents, directories))

In [260]:
remove_doc()

Введите номер документа: 11-2
Документ не найден в базе.
Текущий перечень документов:
№: 2207 876234 , тип: passport , владелец:  Василий Гупкин полка хранения:  1
№: 10006 , тип: insurance , владелец:  Аристарх Павлов полка хранения:  2
None


In [300]:
def doc_moove(directories, documents):
    doc_number = input('Введите номер документа: ')
    shelf_number = input('Введите номер полки: ')
    if shelf_number not in directories.keys():
        print('Такой полки не существует. Текущий перечень полок:', list(directories.keys()))
    for line in documents:
        if doc_number in line.values():
            exist = 1
            break
        else:
            exist = 0
    if exist == 1:
        old_shelf = location(doc_number, directories)
        directories[shelf_number].append(doc_number)
        directories[old_shelf].remove(doc_number)
        print('Документ перемещен.')
        print('Текущий перечень документов:')
        print(full_info(documents, directories))
    else:
        print('Документ не найден.')
        print('Текущий перечень документов:')
        print(full_info(documents, directories))

Введите номер документа: 11-2
Введите номер полки: 3
Документ перемещен.
Текущий перечень документов:
№: 2207 876234 , тип: passport , владелец:  Василий Гупкин полка хранения:  1
№: 11-2 , тип: invoice , владелец:  Геннадий Покемонов полка хранения:  3
№: 10006 , тип: insurance , владелец:  Аристарх Павлов полка хранения:  2
None


In [301]:
directories.items()

dict_items([('1', ['2207 876234']), ('2', ['10006']), ('3', ['11-2'])])

In [303]:
def main_dop(documents, directories):
    """
    описание функции
    """
    while True:
        comand = input('Введите команду: ')
        if comand == 'p':
            print(owner(documents))
        elif comand == 's':
            print(location(str(input('Введите номер документа: '))), directories)
        elif comand == 'l':
            print(full_info(documents, directories))
        elif comand == 'ads':
            print(shelf(str(input('Введите номер полки: '))), directories)
        elif comand == 'ds':
            print(remove(directories))
        elif comand == 'q':
            break
        elif comand == 'ad':
            print(add_doc(documents, directories))
        elif comand == 'd':
            print(remove_doc(documents, directories))
        elif comand == 'm':
            print(doc_moove(directories, documents))
        else:
            print('Такой команды нет')

In [305]:
?main_dop(documents, directories)

Object `main_dop(documents, directories)` not found.


#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.